// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service/battle_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace M3Online.Grpc.BattleService {

  /// <summary>Holder for reflection information generated from service/battle_service.proto</summary>
  public static partial class BattleServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service/battle_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxzZXJ2aWNlL2JhdHRsZV9zZXJ2aWNlLnByb3RvGhJkb21haW4vZW50ZXIu",
            "cHJvdG8iIAoMRW50ZXJSZXF1ZXN0EhAKCGJhdHRsZUlkGAEgASgJIiYKDUVu",
            "dGVyUmVzcG9uc2USFQoFZW50ZXIYASABKAsyBi5FbnRlcjI/Cg1CYXR0bGVT",
            "ZXJ2aWNlEi4KC0VudGVyQmF0dGxlEg0uRW50ZXJSZXF1ZXN0Gg4uRW50ZXJS",
            "ZXNwb25zZSIAQixaDG0zb25saW5lL3JwY6oCG00zT25saW5lLkdycGMuQmF0",
            "dGxlU2VydmljZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::M3Online.Domain.Enter.EnterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::M3Online.Grpc.BattleService.EnterRequest), global::M3Online.Grpc.BattleService.EnterRequest.Parser, new[]{ "BattleId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::M3Online.Grpc.BattleService.EnterResponse), global::M3Online.Grpc.BattleService.EnterResponse.Parser, new[]{ "Enter" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EnterRequest : pb::IMessage<EnterRequest> {
    private static readonly pb::MessageParser<EnterRequest> _parser = new pb::MessageParser<EnterRequest>(() => new EnterRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EnterRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::M3Online.Grpc.BattleService.BattleServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterRequest(EnterRequest other) : this() {
      battleId_ = other.battleId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterRequest Clone() {
      return new EnterRequest(this);
    }

    /// <summary>Field number for the "battleId" field.</summary>
    public const int BattleIdFieldNumber = 1;
    private string battleId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BattleId {
      get { return battleId_; }
      set {
        battleId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EnterRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EnterRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BattleId != other.BattleId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BattleId.Length != 0) hash ^= BattleId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BattleId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BattleId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BattleId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BattleId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EnterRequest other) {
      if (other == null) {
        return;
      }
      if (other.BattleId.Length != 0) {
        BattleId = other.BattleId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            BattleId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class EnterResponse : pb::IMessage<EnterResponse> {
    private static readonly pb::MessageParser<EnterResponse> _parser = new pb::MessageParser<EnterResponse>(() => new EnterResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EnterResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::M3Online.Grpc.BattleService.BattleServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterResponse(EnterResponse other) : this() {
      enter_ = other.enter_ != null ? other.enter_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterResponse Clone() {
      return new EnterResponse(this);
    }

    /// <summary>Field number for the "enter" field.</summary>
    public const int EnterFieldNumber = 1;
    private global::M3Online.Domain.Enter.Enter enter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::M3Online.Domain.Enter.Enter Enter {
      get { return enter_; }
      set {
        enter_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EnterResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EnterResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Enter, other.Enter)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (enter_ != null) hash ^= Enter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (enter_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Enter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (enter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Enter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EnterResponse other) {
      if (other == null) {
        return;
      }
      if (other.enter_ != null) {
        if (enter_ == null) {
          Enter = new global::M3Online.Domain.Enter.Enter();
        }
        Enter.MergeFrom(other.Enter);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (enter_ == null) {
              Enter = new global::M3Online.Domain.Enter.Enter();
            }
            input.ReadMessage(Enter);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
