// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service/battle_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace M3Online.Grpc.BattleService {

  /// <summary>Holder for reflection information generated from service/battle_service.proto</summary>
  public static partial class BattleServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service/battle_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxzZXJ2aWNlL2JhdHRsZV9zZXJ2aWNlLnByb3RvGhJkb21haW4vZW50ZXIu",
            "cHJvdG8aEmRvbWFpbi9lbmVteS5wcm90bxoTZG9tYWluL2F0dGFjay5wcm90",
            "bxoRZG9tYWluL3VzZXIucHJvdG8iMwoMRW50ZXJSZXF1ZXN0EhAKCGJhdHRs",
            "ZUlkGAEgASgJEhEKCXVzZXJfbmFtZRgCIAEoCSImCg1FbnRlclJlc3BvbnNl",
            "EhUKBWVudGVyGAEgASgLMgYuRW50ZXIiKgoRQ29ubmVjdGlvblJlcXVlc3QS",
            "FQoFZW50ZXIYASABKAsyBi5FbnRlciInCg5FbmVteVNpdHVhdGlvbhIVCgVl",
            "bmVteRgBIAEoCzIGLkVuZW15IigKDUF0dGFja1JlcXVlc3QSFwoGYXR0YWNr",
            "GAEgASgLMgcuQXR0YWNrIiUKDlNlc3Npb25TdW1tYXJ5EhMKC3RvdGFsQXR0",
            "YWNrGAEgASgFImsKCFVzZXJMaXN0EigKCHVzZXJfbWFwGAEgAygLMhYuVXNl",
            "ckxpc3QuVXNlck1hcEVudHJ5GjUKDFVzZXJNYXBFbnRyeRILCgNrZXkYASAB",
            "KA0SFAoFdmFsdWUYAiABKAsyBS5Vc2VyOgI4ASIkCgtFeGl0UmVxdWVzdBIV",
            "CgVlbnRlchgBIAEoCzIGLkVudGVyIisKDEV4aXRSZXNwb25zZRIbCgZyZXN1",
            "bHQYASABKA4yCy5SZXN1bHRDb2RlKjEKClJlc3VsdENvZGUSCwoHVU5LTk9X",
            "ThAAEgsKB1NVQ0NFU1MQARIJCgVFUlJPUhACMvwBCg1CYXR0bGVTZXJ2aWNl",
            "Ei4KC0VudGVyQmF0dGxlEg0uRW50ZXJSZXF1ZXN0Gg4uRW50ZXJSZXNwb25z",
            "ZSIAEjIKB0Nvbm5lY3QSEi5Db25uZWN0aW9uUmVxdWVzdBoPLkVuZW15U2l0",
            "dWF0aW9uIgAwARItCgZBdHRhY2sSDi5BdHRhY2tSZXF1ZXN0Gg8uU2Vzc2lv",
            "blN1bW1hcnkiACgBEjEKDFJlY2VpdmVVc2VycxISLkNvbm5lY3Rpb25SZXF1",
            "ZXN0GgkuVXNlckxpc3QiADABEiUKBEV4aXQSDC5FeGl0UmVxdWVzdBoNLkV4",
            "aXRSZXNwb25zZSIAQixaDG0zb25saW5lL3JwY6oCG00zT25saW5lLkdycGMu",
            "QmF0dGxlU2VydmljZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::M3Online.Domain.Enter.EnterReflection.Descriptor, global::M3Online.Domain.Enemy.EnemyReflection.Descriptor, global::M3Online.Domain.Attack.AttackReflection.Descriptor, global::M3Online.Domain.User.UserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::M3Online.Grpc.BattleService.ResultCode), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::M3Online.Grpc.BattleService.EnterRequest), global::M3Online.Grpc.BattleService.EnterRequest.Parser, new[]{ "BattleId", "UserName" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::M3Online.Grpc.BattleService.EnterResponse), global::M3Online.Grpc.BattleService.EnterResponse.Parser, new[]{ "Enter" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::M3Online.Grpc.BattleService.ConnectionRequest), global::M3Online.Grpc.BattleService.ConnectionRequest.Parser, new[]{ "Enter" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::M3Online.Grpc.BattleService.EnemySituation), global::M3Online.Grpc.BattleService.EnemySituation.Parser, new[]{ "Enemy" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::M3Online.Grpc.BattleService.AttackRequest), global::M3Online.Grpc.BattleService.AttackRequest.Parser, new[]{ "Attack" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::M3Online.Grpc.BattleService.SessionSummary), global::M3Online.Grpc.BattleService.SessionSummary.Parser, new[]{ "TotalAttack" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::M3Online.Grpc.BattleService.UserList), global::M3Online.Grpc.BattleService.UserList.Parser, new[]{ "UserMap" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::M3Online.Grpc.BattleService.ExitRequest), global::M3Online.Grpc.BattleService.ExitRequest.Parser, new[]{ "Enter" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::M3Online.Grpc.BattleService.ExitResponse), global::M3Online.Grpc.BattleService.ExitResponse.Parser, new[]{ "Result" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ResultCode {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("SUCCESS")] Success = 1,
    [pbr::OriginalName("ERROR")] Error = 2,
  }

  #endregion

  #region Messages
  public sealed partial class EnterRequest : pb::IMessage<EnterRequest> {
    private static readonly pb::MessageParser<EnterRequest> _parser = new pb::MessageParser<EnterRequest>(() => new EnterRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EnterRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::M3Online.Grpc.BattleService.BattleServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterRequest(EnterRequest other) : this() {
      battleId_ = other.battleId_;
      userName_ = other.userName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterRequest Clone() {
      return new EnterRequest(this);
    }

    /// <summary>Field number for the "battleId" field.</summary>
    public const int BattleIdFieldNumber = 1;
    private string battleId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BattleId {
      get { return battleId_; }
      set {
        battleId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_name" field.</summary>
    public const int UserNameFieldNumber = 2;
    private string userName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserName {
      get { return userName_; }
      set {
        userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EnterRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EnterRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BattleId != other.BattleId) return false;
      if (UserName != other.UserName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BattleId.Length != 0) hash ^= BattleId.GetHashCode();
      if (UserName.Length != 0) hash ^= UserName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BattleId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BattleId);
      }
      if (UserName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BattleId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BattleId);
      }
      if (UserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EnterRequest other) {
      if (other == null) {
        return;
      }
      if (other.BattleId.Length != 0) {
        BattleId = other.BattleId;
      }
      if (other.UserName.Length != 0) {
        UserName = other.UserName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            BattleId = input.ReadString();
            break;
          }
          case 18: {
            UserName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class EnterResponse : pb::IMessage<EnterResponse> {
    private static readonly pb::MessageParser<EnterResponse> _parser = new pb::MessageParser<EnterResponse>(() => new EnterResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EnterResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::M3Online.Grpc.BattleService.BattleServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterResponse(EnterResponse other) : this() {
      enter_ = other.enter_ != null ? other.enter_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterResponse Clone() {
      return new EnterResponse(this);
    }

    /// <summary>Field number for the "enter" field.</summary>
    public const int EnterFieldNumber = 1;
    private global::M3Online.Domain.Enter.Enter enter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::M3Online.Domain.Enter.Enter Enter {
      get { return enter_; }
      set {
        enter_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EnterResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EnterResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Enter, other.Enter)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (enter_ != null) hash ^= Enter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (enter_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Enter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (enter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Enter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EnterResponse other) {
      if (other == null) {
        return;
      }
      if (other.enter_ != null) {
        if (enter_ == null) {
          Enter = new global::M3Online.Domain.Enter.Enter();
        }
        Enter.MergeFrom(other.Enter);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (enter_ == null) {
              Enter = new global::M3Online.Domain.Enter.Enter();
            }
            input.ReadMessage(Enter);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ConnectionRequest : pb::IMessage<ConnectionRequest> {
    private static readonly pb::MessageParser<ConnectionRequest> _parser = new pb::MessageParser<ConnectionRequest>(() => new ConnectionRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConnectionRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::M3Online.Grpc.BattleService.BattleServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectionRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectionRequest(ConnectionRequest other) : this() {
      enter_ = other.enter_ != null ? other.enter_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectionRequest Clone() {
      return new ConnectionRequest(this);
    }

    /// <summary>Field number for the "enter" field.</summary>
    public const int EnterFieldNumber = 1;
    private global::M3Online.Domain.Enter.Enter enter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::M3Online.Domain.Enter.Enter Enter {
      get { return enter_; }
      set {
        enter_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConnectionRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConnectionRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Enter, other.Enter)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (enter_ != null) hash ^= Enter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (enter_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Enter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (enter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Enter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConnectionRequest other) {
      if (other == null) {
        return;
      }
      if (other.enter_ != null) {
        if (enter_ == null) {
          Enter = new global::M3Online.Domain.Enter.Enter();
        }
        Enter.MergeFrom(other.Enter);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (enter_ == null) {
              Enter = new global::M3Online.Domain.Enter.Enter();
            }
            input.ReadMessage(Enter);
            break;
          }
        }
      }
    }

  }

  public sealed partial class EnemySituation : pb::IMessage<EnemySituation> {
    private static readonly pb::MessageParser<EnemySituation> _parser = new pb::MessageParser<EnemySituation>(() => new EnemySituation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EnemySituation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::M3Online.Grpc.BattleService.BattleServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnemySituation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnemySituation(EnemySituation other) : this() {
      enemy_ = other.enemy_ != null ? other.enemy_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnemySituation Clone() {
      return new EnemySituation(this);
    }

    /// <summary>Field number for the "enemy" field.</summary>
    public const int EnemyFieldNumber = 1;
    private global::M3Online.Domain.Enemy.Enemy enemy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::M3Online.Domain.Enemy.Enemy Enemy {
      get { return enemy_; }
      set {
        enemy_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EnemySituation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EnemySituation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Enemy, other.Enemy)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (enemy_ != null) hash ^= Enemy.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (enemy_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Enemy);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (enemy_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Enemy);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EnemySituation other) {
      if (other == null) {
        return;
      }
      if (other.enemy_ != null) {
        if (enemy_ == null) {
          Enemy = new global::M3Online.Domain.Enemy.Enemy();
        }
        Enemy.MergeFrom(other.Enemy);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (enemy_ == null) {
              Enemy = new global::M3Online.Domain.Enemy.Enemy();
            }
            input.ReadMessage(Enemy);
            break;
          }
        }
      }
    }

  }

  public sealed partial class AttackRequest : pb::IMessage<AttackRequest> {
    private static readonly pb::MessageParser<AttackRequest> _parser = new pb::MessageParser<AttackRequest>(() => new AttackRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AttackRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::M3Online.Grpc.BattleService.BattleServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttackRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttackRequest(AttackRequest other) : this() {
      attack_ = other.attack_ != null ? other.attack_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttackRequest Clone() {
      return new AttackRequest(this);
    }

    /// <summary>Field number for the "attack" field.</summary>
    public const int AttackFieldNumber = 1;
    private global::M3Online.Domain.Attack.Attack attack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::M3Online.Domain.Attack.Attack Attack {
      get { return attack_; }
      set {
        attack_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AttackRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AttackRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Attack, other.Attack)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (attack_ != null) hash ^= Attack.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (attack_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Attack);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (attack_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Attack);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AttackRequest other) {
      if (other == null) {
        return;
      }
      if (other.attack_ != null) {
        if (attack_ == null) {
          Attack = new global::M3Online.Domain.Attack.Attack();
        }
        Attack.MergeFrom(other.Attack);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (attack_ == null) {
              Attack = new global::M3Online.Domain.Attack.Attack();
            }
            input.ReadMessage(Attack);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SessionSummary : pb::IMessage<SessionSummary> {
    private static readonly pb::MessageParser<SessionSummary> _parser = new pb::MessageParser<SessionSummary>(() => new SessionSummary());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SessionSummary> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::M3Online.Grpc.BattleService.BattleServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SessionSummary() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SessionSummary(SessionSummary other) : this() {
      totalAttack_ = other.totalAttack_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SessionSummary Clone() {
      return new SessionSummary(this);
    }

    /// <summary>Field number for the "totalAttack" field.</summary>
    public const int TotalAttackFieldNumber = 1;
    private int totalAttack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TotalAttack {
      get { return totalAttack_; }
      set {
        totalAttack_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SessionSummary);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SessionSummary other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TotalAttack != other.TotalAttack) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TotalAttack != 0) hash ^= TotalAttack.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TotalAttack != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TotalAttack);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TotalAttack != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TotalAttack);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SessionSummary other) {
      if (other == null) {
        return;
      }
      if (other.TotalAttack != 0) {
        TotalAttack = other.TotalAttack;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TotalAttack = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class UserList : pb::IMessage<UserList> {
    private static readonly pb::MessageParser<UserList> _parser = new pb::MessageParser<UserList>(() => new UserList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::M3Online.Grpc.BattleService.BattleServiceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserList(UserList other) : this() {
      userMap_ = other.userMap_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserList Clone() {
      return new UserList(this);
    }

    /// <summary>Field number for the "user_map" field.</summary>
    public const int UserMapFieldNumber = 1;
    private static readonly pbc::MapField<uint, global::M3Online.Domain.User.User>.Codec _map_userMap_codec
        = new pbc::MapField<uint, global::M3Online.Domain.User.User>.Codec(pb::FieldCodec.ForUInt32(8), pb::FieldCodec.ForMessage(18, global::M3Online.Domain.User.User.Parser), 10);
    private readonly pbc::MapField<uint, global::M3Online.Domain.User.User> userMap_ = new pbc::MapField<uint, global::M3Online.Domain.User.User>();
    /// <summary>
    ///KeyはEnter.EnterId
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<uint, global::M3Online.Domain.User.User> UserMap {
      get { return userMap_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!UserMap.Equals(other.UserMap)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= UserMap.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      userMap_.WriteTo(output, _map_userMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += userMap_.CalculateSize(_map_userMap_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserList other) {
      if (other == null) {
        return;
      }
      userMap_.Add(other.userMap_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            userMap_.AddEntriesFrom(input, _map_userMap_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ExitRequest : pb::IMessage<ExitRequest> {
    private static readonly pb::MessageParser<ExitRequest> _parser = new pb::MessageParser<ExitRequest>(() => new ExitRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ExitRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::M3Online.Grpc.BattleService.BattleServiceReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExitRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExitRequest(ExitRequest other) : this() {
      enter_ = other.enter_ != null ? other.enter_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExitRequest Clone() {
      return new ExitRequest(this);
    }

    /// <summary>Field number for the "enter" field.</summary>
    public const int EnterFieldNumber = 1;
    private global::M3Online.Domain.Enter.Enter enter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::M3Online.Domain.Enter.Enter Enter {
      get { return enter_; }
      set {
        enter_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ExitRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ExitRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Enter, other.Enter)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (enter_ != null) hash ^= Enter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (enter_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Enter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (enter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Enter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ExitRequest other) {
      if (other == null) {
        return;
      }
      if (other.enter_ != null) {
        if (enter_ == null) {
          Enter = new global::M3Online.Domain.Enter.Enter();
        }
        Enter.MergeFrom(other.Enter);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (enter_ == null) {
              Enter = new global::M3Online.Domain.Enter.Enter();
            }
            input.ReadMessage(Enter);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ExitResponse : pb::IMessage<ExitResponse> {
    private static readonly pb::MessageParser<ExitResponse> _parser = new pb::MessageParser<ExitResponse>(() => new ExitResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ExitResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::M3Online.Grpc.BattleService.BattleServiceReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExitResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExitResponse(ExitResponse other) : this() {
      result_ = other.result_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExitResponse Clone() {
      return new ExitResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::M3Online.Grpc.BattleService.ResultCode result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::M3Online.Grpc.BattleService.ResultCode Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ExitResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ExitResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ExitResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::M3Online.Grpc.BattleService.ResultCode) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
