// Code generated by protoc-gen-go. DO NOT EDIT.
// source: domain/attack.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Attack struct {
	Enter                *Enter   `protobuf:"bytes,1,opt,name=enter,proto3" json:"enter,omitempty"`
	AttackEnemy          *Enemy   `protobuf:"bytes,2,opt,name=attack_enemy,json=attackEnemy,proto3" json:"attack_enemy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attack) Reset()         { *m = Attack{} }
func (m *Attack) String() string { return proto.CompactTextString(m) }
func (*Attack) ProtoMessage()    {}
func (*Attack) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cfea9e5d74e3a3c, []int{0}
}

func (m *Attack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attack.Unmarshal(m, b)
}
func (m *Attack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attack.Marshal(b, m, deterministic)
}
func (m *Attack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attack.Merge(m, src)
}
func (m *Attack) XXX_Size() int {
	return xxx_messageInfo_Attack.Size(m)
}
func (m *Attack) XXX_DiscardUnknown() {
	xxx_messageInfo_Attack.DiscardUnknown(m)
}

var xxx_messageInfo_Attack proto.InternalMessageInfo

func (m *Attack) GetEnter() *Enter {
	if m != nil {
		return m.Enter
	}
	return nil
}

func (m *Attack) GetAttackEnemy() *Enemy {
	if m != nil {
		return m.AttackEnemy
	}
	return nil
}

func init() {
	proto.RegisterType((*Attack)(nil), "Attack")
}

func init() { proto.RegisterFile("domain/attack.proto", fileDescriptor_1cfea9e5d74e3a3c) }

var fileDescriptor_1cfea9e5d74e3a3c = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xc9, 0xcf, 0x4d,
	0xcc, 0xcc, 0xd3, 0x4f, 0x2c, 0x29, 0x49, 0x4c, 0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97,
	0x12, 0x82, 0x0a, 0xa6, 0xe6, 0x95, 0xa4, 0x16, 0x61, 0x88, 0xa5, 0xe6, 0x56, 0x42, 0xc4, 0x94,
	0x02, 0xb9, 0xd8, 0x1c, 0xc1, 0xfa, 0x84, 0x64, 0xb8, 0x58, 0xc1, 0x8a, 0x25, 0x18, 0x15, 0x18,
	0x35, 0xb8, 0x8d, 0xd8, 0xf4, 0x5c, 0x41, 0xbc, 0x20, 0x88, 0xa0, 0x90, 0x26, 0x17, 0x0f, 0xc4,
	0xfc, 0x78, 0xb0, 0x6e, 0x09, 0x26, 0xb8, 0xa2, 0xd4, 0xdc, 0xca, 0x20, 0x6e, 0x88, 0x1c, 0x98,
	0xe3, 0xa4, 0x1e, 0xc5, 0x93, 0x6b, 0x9c, 0x9f, 0x97, 0x93, 0x99, 0x97, 0xaa, 0x5f, 0x54, 0x90,
	0xbc, 0x8a, 0x49, 0xcc, 0xd7, 0xd8, 0x1f, 0xcc, 0xd5, 0x73, 0x01, 0x3b, 0x40, 0x0f, 0x62, 0x63,
	0x12, 0x1b, 0xd8, 0x09, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x96, 0x1e, 0x94, 0xb2, 0xc1,
	0x00, 0x00, 0x00,
}
