// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/battle_service.proto

package rpc

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnterRequest struct {
	BattleId             string   `protobuf:"bytes,1,opt,name=battleId,proto3" json:"battleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterRequest) Reset()         { *m = EnterRequest{} }
func (m *EnterRequest) String() string { return proto.CompactTextString(m) }
func (*EnterRequest) ProtoMessage()    {}
func (*EnterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c471dcc1ccdbdac8, []int{0}
}

func (m *EnterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRequest.Unmarshal(m, b)
}
func (m *EnterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRequest.Marshal(b, m, deterministic)
}
func (m *EnterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRequest.Merge(m, src)
}
func (m *EnterRequest) XXX_Size() int {
	return xxx_messageInfo_EnterRequest.Size(m)
}
func (m *EnterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRequest proto.InternalMessageInfo

func (m *EnterRequest) GetBattleId() string {
	if m != nil {
		return m.BattleId
	}
	return ""
}

type EnterResponse struct {
	Enter                *Enter   `protobuf:"bytes,1,opt,name=enter,proto3" json:"enter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterResponse) Reset()         { *m = EnterResponse{} }
func (m *EnterResponse) String() string { return proto.CompactTextString(m) }
func (*EnterResponse) ProtoMessage()    {}
func (*EnterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c471dcc1ccdbdac8, []int{1}
}

func (m *EnterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterResponse.Unmarshal(m, b)
}
func (m *EnterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterResponse.Marshal(b, m, deterministic)
}
func (m *EnterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterResponse.Merge(m, src)
}
func (m *EnterResponse) XXX_Size() int {
	return xxx_messageInfo_EnterResponse.Size(m)
}
func (m *EnterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnterResponse proto.InternalMessageInfo

func (m *EnterResponse) GetEnter() *Enter {
	if m != nil {
		return m.Enter
	}
	return nil
}

func init() {
	proto.RegisterType((*EnterRequest)(nil), "EnterRequest")
	proto.RegisterType((*EnterResponse)(nil), "EnterResponse")
}

func init() { proto.RegisterFile("service/battle_service.proto", fileDescriptor_c471dcc1ccdbdac8) }

var fileDescriptor_c471dcc1ccdbdac8 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x4f, 0x4a, 0x2c, 0x29, 0xc9, 0x49, 0x8d, 0x87, 0x72, 0xf5, 0x0a, 0x8a,
	0xf2, 0x4b, 0xf2, 0xa5, 0x84, 0x52, 0xf2, 0x73, 0x13, 0x33, 0xf3, 0xf4, 0x53, 0xf3, 0x4a, 0x52,
	0x8b, 0x20, 0x62, 0x4a, 0x5a, 0x5c, 0x3c, 0xae, 0x20, 0x6e, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71,
	0x89, 0x90, 0x14, 0x17, 0x07, 0x44, 0xaf, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10,
	0x9c, 0xaf, 0xa4, 0xcb, 0xc5, 0x0b, 0x55, 0x5b, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc3,
	0xc5, 0x0a, 0x36, 0x0b, 0xac, 0x92, 0xdb, 0x88, 0x4d, 0x0f, 0x22, 0x0d, 0x11, 0x34, 0xb2, 0xe7,
	0xe2, 0x75, 0x02, 0x6b, 0x0d, 0x86, 0xb8, 0x42, 0x48, 0x8f, 0x8b, 0x1b, 0xac, 0x00, 0x22, 0x2a,
	0xc4, 0xab, 0x87, 0x6c, 0xb3, 0x14, 0x9f, 0x1e, 0x8a, 0xe1, 0x4a, 0x0c, 0x4e, 0x3a, 0x51, 0x3c,
	0xb9, 0xc6, 0xf9, 0x79, 0x39, 0x99, 0x79, 0xa9, 0xfa, 0x45, 0x05, 0xc9, 0xab, 0x98, 0xa4, 0x7d,
	0x8d, 0xfd, 0xc1, 0x5c, 0x3d, 0xf7, 0xa2, 0x82, 0x64, 0x3d, 0x14, 0xd3, 0x93, 0xd8, 0xc0, 0x1e,
	0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xdf, 0x3c, 0x02, 0x04, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BattleServiceClient is the client API for BattleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BattleServiceClient interface {
	EnterBattle(ctx context.Context, in *EnterRequest, opts ...grpc.CallOption) (*EnterResponse, error)
}

type battleServiceClient struct {
	cc *grpc.ClientConn
}

func NewBattleServiceClient(cc *grpc.ClientConn) BattleServiceClient {
	return &battleServiceClient{cc}
}

func (c *battleServiceClient) EnterBattle(ctx context.Context, in *EnterRequest, opts ...grpc.CallOption) (*EnterResponse, error) {
	out := new(EnterResponse)
	err := c.cc.Invoke(ctx, "/BattleService/EnterBattle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BattleServiceServer is the server API for BattleService service.
type BattleServiceServer interface {
	EnterBattle(context.Context, *EnterRequest) (*EnterResponse, error)
}

// UnimplementedBattleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBattleServiceServer struct {
}

func (*UnimplementedBattleServiceServer) EnterBattle(ctx context.Context, req *EnterRequest) (*EnterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnterBattle not implemented")
}

func RegisterBattleServiceServer(s *grpc.Server, srv BattleServiceServer) {
	s.RegisterService(&_BattleService_serviceDesc, srv)
}

func _BattleService_EnterBattle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).EnterBattle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BattleService/EnterBattle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).EnterBattle(ctx, req.(*EnterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BattleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BattleService",
	HandlerType: (*BattleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnterBattle",
			Handler:    _BattleService_EnterBattle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/battle_service.proto",
}
