// Code generated by protoc-gen-go. DO NOT EDIT.
// source: domain/enter.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Enter struct {
	EnterId              uint32   `protobuf:"varint,1,opt,name=enter_id,json=enterId,proto3" json:"enter_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Enter) Reset()         { *m = Enter{} }
func (m *Enter) String() string { return proto.CompactTextString(m) }
func (*Enter) ProtoMessage()    {}
func (*Enter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0b61c6da150df02, []int{0}
}

func (m *Enter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Enter.Unmarshal(m, b)
}
func (m *Enter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Enter.Marshal(b, m, deterministic)
}
func (m *Enter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Enter.Merge(m, src)
}
func (m *Enter) XXX_Size() int {
	return xxx_messageInfo_Enter.Size(m)
}
func (m *Enter) XXX_DiscardUnknown() {
	xxx_messageInfo_Enter.DiscardUnknown(m)
}

var xxx_messageInfo_Enter proto.InternalMessageInfo

func (m *Enter) GetEnterId() uint32 {
	if m != nil {
		return m.EnterId
	}
	return 0
}

func init() {
	proto.RegisterType((*Enter)(nil), "Enter")
}

func init() { proto.RegisterFile("domain/enter.proto", fileDescriptor_d0b61c6da150df02) }

var fileDescriptor_d0b61c6da150df02 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xc9, 0xcf, 0x4d,
	0xcc, 0xcc, 0xd3, 0x4f, 0xcd, 0x2b, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52,
	0xe2, 0x62, 0x75, 0x05, 0x71, 0x85, 0x24, 0xb9, 0x38, 0xc0, 0xe2, 0xf1, 0x99, 0x29, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0xec, 0x60, 0xbe, 0x67, 0x8a, 0x93, 0x5a, 0x14, 0x4f, 0xae, 0x71,
	0x7e, 0x5e, 0x4e, 0x66, 0x5e, 0xaa, 0x7e, 0x51, 0x41, 0xf2, 0x2a, 0x26, 0x51, 0x5f, 0x63, 0x7f,
	0x30, 0x57, 0xcf, 0x05, 0x6c, 0xa2, 0x1e, 0xd8, 0x88, 0x24, 0x36, 0xb0, 0x91, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x0c, 0x5a, 0x3f, 0x51, 0x68, 0x00, 0x00, 0x00,
}
